// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MediaType.proto

// Protobuf Java Version: 3.25.1
package com.hiraeth.im.protocol;

public final class MediaTypeEnum {
  private MediaTypeEnum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code im.MediaType}
   */
  public enum MediaType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *纯文本 / 文本 + 简单预装表情
     * </pre>
     *
     * <code>TEXT = 0;</code>
     */
    TEXT(0),
    /**
     * <pre>
     * 图文
     * </pre>
     *
     * <code>IMAGE_AND_TEXT = 1;</code>
     */
    IMAGE_AND_TEXT(1),
    /**
     * <code>IMAGE = 2;</code>
     */
    IMAGE(2),
    /**
     * <code>VOICE = 3;</code>
     */
    VOICE(3),
    /**
     * <code>VIDEO = 4;</code>
     */
    VIDEO(4),
    /**
     * <code>EMOJI = 5;</code>
     */
    EMOJI(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *纯文本 / 文本 + 简单预装表情
     * </pre>
     *
     * <code>TEXT = 0;</code>
     */
    public static final int TEXT_VALUE = 0;
    /**
     * <pre>
     * 图文
     * </pre>
     *
     * <code>IMAGE_AND_TEXT = 1;</code>
     */
    public static final int IMAGE_AND_TEXT_VALUE = 1;
    /**
     * <code>IMAGE = 2;</code>
     */
    public static final int IMAGE_VALUE = 2;
    /**
     * <code>VOICE = 3;</code>
     */
    public static final int VOICE_VALUE = 3;
    /**
     * <code>VIDEO = 4;</code>
     */
    public static final int VIDEO_VALUE = 4;
    /**
     * <code>EMOJI = 5;</code>
     */
    public static final int EMOJI_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static MediaType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MediaType forNumber(int value) {
      switch (value) {
        case 0: return TEXT;
        case 1: return IMAGE_AND_TEXT;
        case 2: return IMAGE;
        case 3: return VOICE;
        case 4: return VIDEO;
        case 5: return EMOJI;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MediaType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MediaType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MediaType>() {
            public MediaType findValueByNumber(int number) {
              return MediaType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return MediaTypeEnum.getDescriptor().getEnumTypes().get(0);
    }

    private static final MediaType[] VALUES = values();

    public static MediaType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MediaType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:im.MediaType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017MediaType.proto\022\002im*U\n\tMediaType\022\010\n\004TE" +
      "XT\020\000\022\022\n\016IMAGE_AND_TEXT\020\001\022\t\n\005IMAGE\020\002\022\t\n\005V" +
      "OICE\020\003\022\t\n\005VIDEO\020\004\022\t\n\005EMOJI\020\005B(\n\027com.hira" +
      "eth.im.protocolB\rMediaTypeEnumb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
