// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageSendRequest.proto

// Protobuf Java Version: 3.25.1
package com.hiraeth.im.protocol;

public final class MessageSendRequestProto {
  private MessageSendRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageSendRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:im.MessageSendRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string from_uid = 1;</code>
     * @return The fromUid.
     */
    String getFromUid();
    /**
     * <code>string from_uid = 1;</code>
     * @return The bytes for fromUid.
     */
    com.google.protobuf.ByteString
        getFromUidBytes();

    /**
     * <pre>
     * 单聊存放用户id, 群聊存放群id
     * </pre>
     *
     * <code>string to_uid = 2;</code>
     * @return The toUid.
     */
    String getToUid();
    /**
     * <pre>
     * 单聊存放用户id, 群聊存放群id
     * </pre>
     *
     * <code>string to_uid = 2;</code>
     * @return The bytes for toUid.
     */
    com.google.protobuf.ByteString
        getToUidBytes();

    /**
     * <pre>
     * 单聊或群聊
     * </pre>
     *
     * <code>.im.ChatType chat_type = 3;</code>
     * @return The enum numeric value on the wire for chatType.
     */
    int getChatTypeValue();
    /**
     * <pre>
     * 单聊或群聊
     * </pre>
     *
     * <code>.im.ChatType chat_type = 3;</code>
     * @return The chatType.
     */
    ChatTypeEnum.ChatType getChatType();

    /**
     * <code>int32 group_id = 4;</code>
     * @return The groupId.
     */
    int getGroupId();

    /**
     * <code>int64 timestamp = 5;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>.im.MediaType media_type = 6;</code>
     * @return The enum numeric value on the wire for mediaType.
     */
    int getMediaTypeValue();
    /**
     * <code>.im.MediaType media_type = 6;</code>
     * @return The mediaType.
     */
    MediaTypeEnum.MediaType getMediaType();

    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 7;</code>
     * @return The content.
     */
    String getContent();
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 7;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 视频, 语音, 图片, 表情等文件地址
     * </pre>
     *
     * <code>string file_path = 8;</code>
     * @return The filePath.
     */
    String getFilePath();
    /**
     * <pre>
     * 视频, 语音, 图片, 表情等文件地址
     * </pre>
     *
     * <code>string file_path = 8;</code>
     * @return The bytes for filePath.
     */
    com.google.protobuf.ByteString
        getFilePathBytes();
  }
  /**
   * Protobuf type {@code im.MessageSendRequest}
   */
  public static final class MessageSendRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:im.MessageSendRequest)
      MessageSendRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageSendRequest.newBuilder() to construct.
    private MessageSendRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageSendRequest() {
      fromUid_ = "";
      toUid_ = "";
      chatType_ = 0;
      mediaType_ = 0;
      content_ = "";
      filePath_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageSendRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageSendRequestProto.internal_static_im_MessageSendRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageSendRequestProto.internal_static_im_MessageSendRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageSendRequest.class, Builder.class);
    }

    public static final int FROM_UID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object fromUid_ = "";
    /**
     * <code>string from_uid = 1;</code>
     * @return The fromUid.
     */
    @Override
    public String getFromUid() {
      Object ref = fromUid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fromUid_ = s;
        return s;
      }
    }
    /**
     * <code>string from_uid = 1;</code>
     * @return The bytes for fromUid.
     */
    @Override
    public com.google.protobuf.ByteString
        getFromUidBytes() {
      Object ref = fromUid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fromUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_UID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object toUid_ = "";
    /**
     * <pre>
     * 单聊存放用户id, 群聊存放群id
     * </pre>
     *
     * <code>string to_uid = 2;</code>
     * @return The toUid.
     */
    @Override
    public String getToUid() {
      Object ref = toUid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        toUid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 单聊存放用户id, 群聊存放群id
     * </pre>
     *
     * <code>string to_uid = 2;</code>
     * @return The bytes for toUid.
     */
    @Override
    public com.google.protobuf.ByteString
        getToUidBytes() {
      Object ref = toUid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        toUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHAT_TYPE_FIELD_NUMBER = 3;
    private int chatType_ = 0;
    /**
     * <pre>
     * 单聊或群聊
     * </pre>
     *
     * <code>.im.ChatType chat_type = 3;</code>
     * @return The enum numeric value on the wire for chatType.
     */
    @Override public int getChatTypeValue() {
      return chatType_;
    }
    /**
     * <pre>
     * 单聊或群聊
     * </pre>
     *
     * <code>.im.ChatType chat_type = 3;</code>
     * @return The chatType.
     */
    @Override public ChatTypeEnum.ChatType getChatType() {
      ChatTypeEnum.ChatType result = ChatTypeEnum.ChatType.forNumber(chatType_);
      return result == null ? ChatTypeEnum.ChatType.UNRECOGNIZED : result;
    }

    public static final int GROUP_ID_FIELD_NUMBER = 4;
    private int groupId_ = 0;
    /**
     * <code>int32 group_id = 4;</code>
     * @return The groupId.
     */
    @Override
    public int getGroupId() {
      return groupId_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timestamp_ = 0L;
    /**
     * <code>int64 timestamp = 5;</code>
     * @return The timestamp.
     */
    @Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int MEDIA_TYPE_FIELD_NUMBER = 6;
    private int mediaType_ = 0;
    /**
     * <code>.im.MediaType media_type = 6;</code>
     * @return The enum numeric value on the wire for mediaType.
     */
    @Override public int getMediaTypeValue() {
      return mediaType_;
    }
    /**
     * <code>.im.MediaType media_type = 6;</code>
     * @return The mediaType.
     */
    @Override public MediaTypeEnum.MediaType getMediaType() {
      MediaTypeEnum.MediaType result = MediaTypeEnum.MediaType.forNumber(mediaType_);
      return result == null ? MediaTypeEnum.MediaType.UNRECOGNIZED : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile Object content_ = "";
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 7;</code>
     * @return The content.
     */
    @Override
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 7;</code>
     * @return The bytes for content.
     */
    @Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILE_PATH_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile Object filePath_ = "";
    /**
     * <pre>
     * 视频, 语音, 图片, 表情等文件地址
     * </pre>
     *
     * <code>string file_path = 8;</code>
     * @return The filePath.
     */
    @Override
    public String getFilePath() {
      Object ref = filePath_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        filePath_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 视频, 语音, 图片, 表情等文件地址
     * </pre>
     *
     * <code>string file_path = 8;</code>
     * @return The bytes for filePath.
     */
    @Override
    public com.google.protobuf.ByteString
        getFilePathBytes() {
      Object ref = filePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromUid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fromUid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(toUid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, toUid_);
      }
      if (chatType_ != ChatTypeEnum.ChatType.SINGLE.getNumber()) {
        output.writeEnum(3, chatType_);
      }
      if (groupId_ != 0) {
        output.writeInt32(4, groupId_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(5, timestamp_);
      }
      if (mediaType_ != MediaTypeEnum.MediaType.TEXT.getNumber()) {
        output.writeEnum(6, mediaType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, content_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(filePath_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, filePath_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromUid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fromUid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(toUid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, toUid_);
      }
      if (chatType_ != ChatTypeEnum.ChatType.SINGLE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, chatType_);
      }
      if (groupId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, groupId_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, timestamp_);
      }
      if (mediaType_ != MediaTypeEnum.MediaType.TEXT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, mediaType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, content_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(filePath_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, filePath_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessageSendRequest)) {
        return super.equals(obj);
      }
      MessageSendRequest other = (MessageSendRequest) obj;

      if (!getFromUid()
          .equals(other.getFromUid())) return false;
      if (!getToUid()
          .equals(other.getToUid())) return false;
      if (chatType_ != other.chatType_) return false;
      if (getGroupId()
          != other.getGroupId()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (mediaType_ != other.mediaType_) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getFilePath()
          .equals(other.getFilePath())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROM_UID_FIELD_NUMBER;
      hash = (53 * hash) + getFromUid().hashCode();
      hash = (37 * hash) + TO_UID_FIELD_NUMBER;
      hash = (53 * hash) + getToUid().hashCode();
      hash = (37 * hash) + CHAT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + chatType_;
      hash = (37 * hash) + GROUP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + MEDIA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + mediaType_;
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + FILE_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getFilePath().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessageSendRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageSendRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageSendRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageSendRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageSendRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageSendRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageSendRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageSendRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static MessageSendRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static MessageSendRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageSendRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageSendRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessageSendRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code im.MessageSendRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:im.MessageSendRequest)
        MessageSendRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageSendRequestProto.internal_static_im_MessageSendRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageSendRequestProto.internal_static_im_MessageSendRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageSendRequest.class, Builder.class);
      }

      // Construct using com.hiraeth.im.protocol.MessageSendRequestProto.MessageSendRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fromUid_ = "";
        toUid_ = "";
        chatType_ = 0;
        groupId_ = 0;
        timestamp_ = 0L;
        mediaType_ = 0;
        content_ = "";
        filePath_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageSendRequestProto.internal_static_im_MessageSendRequest_descriptor;
      }

      @Override
      public MessageSendRequest getDefaultInstanceForType() {
        return MessageSendRequest.getDefaultInstance();
      }

      @Override
      public MessageSendRequest build() {
        MessageSendRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MessageSendRequest buildPartial() {
        MessageSendRequest result = new MessageSendRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(MessageSendRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fromUid_ = fromUid_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.toUid_ = toUid_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.chatType_ = chatType_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.groupId_ = groupId_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.timestamp_ = timestamp_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.mediaType_ = mediaType_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.content_ = content_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.filePath_ = filePath_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageSendRequest) {
          return mergeFrom((MessageSendRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageSendRequest other) {
        if (other == MessageSendRequest.getDefaultInstance()) return this;
        if (!other.getFromUid().isEmpty()) {
          fromUid_ = other.fromUid_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getToUid().isEmpty()) {
          toUid_ = other.toUid_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.chatType_ != 0) {
          setChatTypeValue(other.getChatTypeValue());
        }
        if (other.getGroupId() != 0) {
          setGroupId(other.getGroupId());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.mediaType_ != 0) {
          setMediaTypeValue(other.getMediaTypeValue());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (!other.getFilePath().isEmpty()) {
          filePath_ = other.filePath_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                fromUid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                toUid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                chatType_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                groupId_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                mediaType_ = input.readEnum();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 58: {
                content_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                filePath_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object fromUid_ = "";
      /**
       * <code>string from_uid = 1;</code>
       * @return The fromUid.
       */
      public String getFromUid() {
        Object ref = fromUid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fromUid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string from_uid = 1;</code>
       * @return The bytes for fromUid.
       */
      public com.google.protobuf.ByteString
          getFromUidBytes() {
        Object ref = fromUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fromUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string from_uid = 1;</code>
       * @param value The fromUid to set.
       * @return This builder for chaining.
       */
      public Builder setFromUid(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        fromUid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string from_uid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromUid() {
        fromUid_ = getDefaultInstance().getFromUid();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string from_uid = 1;</code>
       * @param value The bytes for fromUid to set.
       * @return This builder for chaining.
       */
      public Builder setFromUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        fromUid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object toUid_ = "";
      /**
       * <pre>
       * 单聊存放用户id, 群聊存放群id
       * </pre>
       *
       * <code>string to_uid = 2;</code>
       * @return The toUid.
       */
      public String getToUid() {
        Object ref = toUid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          toUid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 单聊存放用户id, 群聊存放群id
       * </pre>
       *
       * <code>string to_uid = 2;</code>
       * @return The bytes for toUid.
       */
      public com.google.protobuf.ByteString
          getToUidBytes() {
        Object ref = toUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          toUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 单聊存放用户id, 群聊存放群id
       * </pre>
       *
       * <code>string to_uid = 2;</code>
       * @param value The toUid to set.
       * @return This builder for chaining.
       */
      public Builder setToUid(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        toUid_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 单聊存放用户id, 群聊存放群id
       * </pre>
       *
       * <code>string to_uid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearToUid() {
        toUid_ = getDefaultInstance().getToUid();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 单聊存放用户id, 群聊存放群id
       * </pre>
       *
       * <code>string to_uid = 2;</code>
       * @param value The bytes for toUid to set.
       * @return This builder for chaining.
       */
      public Builder setToUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        toUid_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int chatType_ = 0;
      /**
       * <pre>
       * 单聊或群聊
       * </pre>
       *
       * <code>.im.ChatType chat_type = 3;</code>
       * @return The enum numeric value on the wire for chatType.
       */
      @Override public int getChatTypeValue() {
        return chatType_;
      }
      /**
       * <pre>
       * 单聊或群聊
       * </pre>
       *
       * <code>.im.ChatType chat_type = 3;</code>
       * @param value The enum numeric value on the wire for chatType to set.
       * @return This builder for chaining.
       */
      public Builder setChatTypeValue(int value) {
        chatType_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 单聊或群聊
       * </pre>
       *
       * <code>.im.ChatType chat_type = 3;</code>
       * @return The chatType.
       */
      @Override
      public ChatTypeEnum.ChatType getChatType() {
        ChatTypeEnum.ChatType result = ChatTypeEnum.ChatType.forNumber(chatType_);
        return result == null ? ChatTypeEnum.ChatType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 单聊或群聊
       * </pre>
       *
       * <code>.im.ChatType chat_type = 3;</code>
       * @param value The chatType to set.
       * @return This builder for chaining.
       */
      public Builder setChatType(ChatTypeEnum.ChatType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        chatType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 单聊或群聊
       * </pre>
       *
       * <code>.im.ChatType chat_type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearChatType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        chatType_ = 0;
        onChanged();
        return this;
      }

      private int groupId_ ;
      /**
       * <code>int32 group_id = 4;</code>
       * @return The groupId.
       */
      @Override
      public int getGroupId() {
        return groupId_;
      }
      /**
       * <code>int32 group_id = 4;</code>
       * @param value The groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupId(int value) {

        groupId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 group_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        groupId_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 5;</code>
       * @return The timestamp.
       */
      @Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 5;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int mediaType_ = 0;
      /**
       * <code>.im.MediaType media_type = 6;</code>
       * @return The enum numeric value on the wire for mediaType.
       */
      @Override public int getMediaTypeValue() {
        return mediaType_;
      }
      /**
       * <code>.im.MediaType media_type = 6;</code>
       * @param value The enum numeric value on the wire for mediaType to set.
       * @return This builder for chaining.
       */
      public Builder setMediaTypeValue(int value) {
        mediaType_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.im.MediaType media_type = 6;</code>
       * @return The mediaType.
       */
      @Override
      public MediaTypeEnum.MediaType getMediaType() {
        MediaTypeEnum.MediaType result = MediaTypeEnum.MediaType.forNumber(mediaType_);
        return result == null ? MediaTypeEnum.MediaType.UNRECOGNIZED : result;
      }
      /**
       * <code>.im.MediaType media_type = 6;</code>
       * @param value The mediaType to set.
       * @return This builder for chaining.
       */
      public Builder setMediaType(MediaTypeEnum.MediaType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        mediaType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.im.MediaType media_type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMediaType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        mediaType_ = 0;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 7;</code>
       * @return The content.
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 7;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 7;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        content_ = getDefaultInstance().getContent();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 7;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        content_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private Object filePath_ = "";
      /**
       * <pre>
       * 视频, 语音, 图片, 表情等文件地址
       * </pre>
       *
       * <code>string file_path = 8;</code>
       * @return The filePath.
       */
      public String getFilePath() {
        Object ref = filePath_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          filePath_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 视频, 语音, 图片, 表情等文件地址
       * </pre>
       *
       * <code>string file_path = 8;</code>
       * @return The bytes for filePath.
       */
      public com.google.protobuf.ByteString
          getFilePathBytes() {
        Object ref = filePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          filePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 视频, 语音, 图片, 表情等文件地址
       * </pre>
       *
       * <code>string file_path = 8;</code>
       * @param value The filePath to set.
       * @return This builder for chaining.
       */
      public Builder setFilePath(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        filePath_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 视频, 语音, 图片, 表情等文件地址
       * </pre>
       *
       * <code>string file_path = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilePath() {
        filePath_ = getDefaultInstance().getFilePath();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 视频, 语音, 图片, 表情等文件地址
       * </pre>
       *
       * <code>string file_path = 8;</code>
       * @param value The bytes for filePath to set.
       * @return This builder for chaining.
       */
      public Builder setFilePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        filePath_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:im.MessageSendRequest)
    }

    // @@protoc_insertion_point(class_scope:im.MessageSendRequest)
    private static final MessageSendRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessageSendRequest();
    }

    public static MessageSendRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageSendRequest>
        PARSER = new com.google.protobuf.AbstractParser<MessageSendRequest>() {
      @Override
      public MessageSendRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MessageSendRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MessageSendRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public MessageSendRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_MessageSendRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_MessageSendRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030MessageSendRequest.proto\022\002im\032\016ChatType" +
      ".proto\032\017MediaType.proto\"\303\001\n\022MessageSendR" +
      "equest\022\020\n\010from_uid\030\001 \001(\t\022\016\n\006to_uid\030\002 \001(\t" +
      "\022\037\n\tchat_type\030\003 \001(\0162\014.im.ChatType\022\020\n\010gro" +
      "up_id\030\004 \001(\005\022\021\n\ttimestamp\030\005 \001(\003\022!\n\nmedia_" +
      "type\030\006 \001(\0162\r.im.MediaType\022\017\n\007content\030\007 \001" +
      "(\t\022\021\n\tfile_path\030\010 \001(\tB2\n\027com.hiraeth.im." +
      "protocolB\027MessageSendRequestProtob\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ChatTypeEnum.getDescriptor(),
          MediaTypeEnum.getDescriptor(),
        });
    internal_static_im_MessageSendRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_MessageSendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_MessageSendRequest_descriptor,
        new String[] { "FromUid", "ToUid", "ChatType", "GroupId", "Timestamp", "MediaType", "Content", "FilePath", });
    ChatTypeEnum.getDescriptor();
    MediaTypeEnum.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
