spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_im?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 12345678

    druid:
      async-init: true
      useGlobalDataSourceStat: true
      stat-view-servlet:
        enabled: true
        allow:
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # multi-statement-allow 配置无效，只能通过代码控制
      #      filter:
      #        wall:
      #          config:
      #            multi-statement-allow: true
      #            none-base-statement-allow: true
      # 配置监控统计拦截的filters，stat去掉后监控界面sql无法统计，wall 用于防火墙
      filters: stat,wall,slf4j,mergeStat
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500;druid.stat.logSlowSql=true

  redis:
    #数据库索引
    database: 0
    host: 'localhost'
    port: 6379
    password:
    #连接超时时间,单位ms
    timeout: 10000
    loginTimeout: 86400

    #最大链接数, 默认 50
    #  maxTotal: 100
    #  #最大空闲数，数据库连接的最大空闲时间。超过空闲数量，数据库连接将被标记为不可用，然后被释放。设为0表示无限制
    #  maxIdle: 20
    #  ##jedis的最大活跃连接数设为0表示无限制
    #  maxActive: 100
    #  #最大等待时间：单位ms
    #  #jedis池没有连接对象返回时，等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。
    #  #如果超过等待时间，则直接抛出JedisConnectionException
    #  maxWait: 1000

    jedis:
      pool:
        #最大连接数
        max-active: 500
        #最大阻塞等待时间(负数表示没限制),单位ms
        max-wait: 5000
        #最大空闲
        max-idle: 8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
    call-setters-on-nulls: true
  type-handlers-package:  com.hiraeth.im.business.handler
  global-config:
    banner: false

rocketmq:
  producer:
    group: dispatcher-producer-group
    send-message-timeout: 5000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 3
    # 异步消息重试此处，默认2
    retryTimesWhenSendAsyncFailed: 3
    # 消息最大长度，默认 1024 * 1024 * 4(默认4M)
    maxMessageSize: 4096
    # 压缩消息阈值，默认4k(1024 * 4)
    compressMessageBodyThreshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retryNextServer: false
  name-server: 'localhost:9876'
  consumer:
    max-retry-times: 5

logging:
  level:
    io:
      netty: ERROR
    RocketmqClient: ERROR