// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthenticateRequest.proto

// Protobuf Java Version: 3.25.1
package com.lynch.im.protocol;

public final class AuthenticateRequestProto {
  private AuthenticateRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AuthenticateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:im.AuthenticateRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 clientVersion = 1;</code>
     * @return The clientVersion.
     */
    int getClientVersion();

    /**
     * <code>.im.RequestType requestType = 2;</code>
     * @return The enum numeric value on the wire for requestType.
     */
    int getRequestTypeValue();
    /**
     * <code>.im.RequestType requestType = 2;</code>
     * @return The requestType.
     */
    com.lynch.im.protocol.RequestTypeProto.RequestType getRequestType();

    /**
     * <code>int64 sequence = 3;</code>
     * @return The sequence.
     */
    long getSequence();

    /**
     * <code>string uid = 4;</code>
     * @return The uid.
     */
    java.lang.String getUid();
    /**
     * <code>string uid = 4;</code>
     * @return The bytes for uid.
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <code>string token = 5;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 5;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code im.AuthenticateRequest}
   */
  public static final class AuthenticateRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:im.AuthenticateRequest)
      AuthenticateRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AuthenticateRequest.newBuilder() to construct.
    private AuthenticateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AuthenticateRequest() {
      requestType_ = 0;
      uid_ = "";
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AuthenticateRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lynch.im.protocol.AuthenticateRequestProto.internal_static_im_AuthenticateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lynch.im.protocol.AuthenticateRequestProto.internal_static_im_AuthenticateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest.class, com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest.Builder.class);
    }

    public static final int CLIENTVERSION_FIELD_NUMBER = 1;
    private int clientVersion_ = 0;
    /**
     * <code>int32 clientVersion = 1;</code>
     * @return The clientVersion.
     */
    @java.lang.Override
    public int getClientVersion() {
      return clientVersion_;
    }

    public static final int REQUESTTYPE_FIELD_NUMBER = 2;
    private int requestType_ = 0;
    /**
     * <code>.im.RequestType requestType = 2;</code>
     * @return The enum numeric value on the wire for requestType.
     */
    @java.lang.Override public int getRequestTypeValue() {
      return requestType_;
    }
    /**
     * <code>.im.RequestType requestType = 2;</code>
     * @return The requestType.
     */
    @java.lang.Override public com.lynch.im.protocol.RequestTypeProto.RequestType getRequestType() {
      com.lynch.im.protocol.RequestTypeProto.RequestType result = com.lynch.im.protocol.RequestTypeProto.RequestType.forNumber(requestType_);
      return result == null ? com.lynch.im.protocol.RequestTypeProto.RequestType.UNRECOGNIZED : result;
    }

    public static final int SEQUENCE_FIELD_NUMBER = 3;
    private long sequence_ = 0L;
    /**
     * <code>int64 sequence = 3;</code>
     * @return The sequence.
     */
    @java.lang.Override
    public long getSequence() {
      return sequence_;
    }

    public static final int UID_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object uid_ = "";
    /**
     * <code>string uid = 4;</code>
     * @return The uid.
     */
    @java.lang.Override
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <code>string uid = 4;</code>
     * @return The bytes for uid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object token_ = "";
    /**
     * <code>string token = 5;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 5;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private long timestamp_ = 0L;
    /**
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (clientVersion_ != 0) {
        output.writeInt32(1, clientVersion_);
      }
      if (requestType_ != com.lynch.im.protocol.RequestTypeProto.RequestType.AUTHENTICATE.getNumber()) {
        output.writeEnum(2, requestType_);
      }
      if (sequence_ != 0L) {
        output.writeInt64(3, sequence_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, uid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, token_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(6, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (clientVersion_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, clientVersion_);
      }
      if (requestType_ != com.lynch.im.protocol.RequestTypeProto.RequestType.AUTHENTICATE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, requestType_);
      }
      if (sequence_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sequence_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, uid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, token_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest)) {
        return super.equals(obj);
      }
      com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest other = (com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest) obj;

      if (getClientVersion()
          != other.getClientVersion()) return false;
      if (requestType_ != other.requestType_) return false;
      if (getSequence()
          != other.getSequence()) return false;
      if (!getUid()
          .equals(other.getUid())) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getClientVersion();
      hash = (37 * hash) + REQUESTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + requestType_;
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSequence());
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code im.AuthenticateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:im.AuthenticateRequest)
        com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lynch.im.protocol.AuthenticateRequestProto.internal_static_im_AuthenticateRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lynch.im.protocol.AuthenticateRequestProto.internal_static_im_AuthenticateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest.class, com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest.Builder.class);
      }

      // Construct using com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        clientVersion_ = 0;
        requestType_ = 0;
        sequence_ = 0L;
        uid_ = "";
        token_ = "";
        timestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lynch.im.protocol.AuthenticateRequestProto.internal_static_im_AuthenticateRequest_descriptor;
      }

      @java.lang.Override
      public com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest getDefaultInstanceForType() {
        return com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest build() {
        com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest buildPartial() {
        com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest result = new com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.clientVersion_ = clientVersion_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.requestType_ = requestType_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sequence_ = sequence_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.uid_ = uid_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.token_ = token_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.timestamp_ = timestamp_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest) {
          return mergeFrom((com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest other) {
        if (other == com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest.getDefaultInstance()) return this;
        if (other.getClientVersion() != 0) {
          setClientVersion(other.getClientVersion());
        }
        if (other.requestType_ != 0) {
          setRequestTypeValue(other.getRequestTypeValue());
        }
        if (other.getSequence() != 0L) {
          setSequence(other.getSequence());
        }
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                clientVersion_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                requestType_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                sequence_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                uid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                token_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 48: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int clientVersion_ ;
      /**
       * <code>int32 clientVersion = 1;</code>
       * @return The clientVersion.
       */
      @java.lang.Override
      public int getClientVersion() {
        return clientVersion_;
      }
      /**
       * <code>int32 clientVersion = 1;</code>
       * @param value The clientVersion to set.
       * @return This builder for chaining.
       */
      public Builder setClientVersion(int value) {

        clientVersion_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 clientVersion = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientVersion_ = 0;
        onChanged();
        return this;
      }

      private int requestType_ = 0;
      /**
       * <code>.im.RequestType requestType = 2;</code>
       * @return The enum numeric value on the wire for requestType.
       */
      @java.lang.Override public int getRequestTypeValue() {
        return requestType_;
      }
      /**
       * <code>.im.RequestType requestType = 2;</code>
       * @param value The enum numeric value on the wire for requestType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestTypeValue(int value) {
        requestType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.im.RequestType requestType = 2;</code>
       * @return The requestType.
       */
      @java.lang.Override
      public com.lynch.im.protocol.RequestTypeProto.RequestType getRequestType() {
        com.lynch.im.protocol.RequestTypeProto.RequestType result = com.lynch.im.protocol.RequestTypeProto.RequestType.forNumber(requestType_);
        return result == null ? com.lynch.im.protocol.RequestTypeProto.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.im.RequestType requestType = 2;</code>
       * @param value The requestType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestType(com.lynch.im.protocol.RequestTypeProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        requestType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.im.RequestType requestType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        requestType_ = 0;
        onChanged();
        return this;
      }

      private long sequence_ ;
      /**
       * <code>int64 sequence = 3;</code>
       * @return The sequence.
       */
      @java.lang.Override
      public long getSequence() {
        return sequence_;
      }
      /**
       * <code>int64 sequence = 3;</code>
       * @param value The sequence to set.
       * @return This builder for chaining.
       */
      public Builder setSequence(long value) {

        sequence_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sequence = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSequence() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sequence_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <code>string uid = 4;</code>
       * @return The uid.
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uid = 4;</code>
       * @return The bytes for uid.
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uid = 4;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        uid_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        uid_ = getDefaultInstance().getUid();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 4;</code>
       * @param value The bytes for uid to set.
       * @return This builder for chaining.
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        uid_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 5;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 5;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 5;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        token_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        token_ = getDefaultInstance().getToken();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string token = 5;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        token_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 6;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 6;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:im.AuthenticateRequest)
    }

    // @@protoc_insertion_point(class_scope:im.AuthenticateRequest)
    private static final com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest();
    }

    public static com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuthenticateRequest>
        PARSER = new com.google.protobuf.AbstractParser<AuthenticateRequest>() {
      @java.lang.Override
      public AuthenticateRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AuthenticateRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuthenticateRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lynch.im.protocol.AuthenticateRequestProto.AuthenticateRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_AuthenticateRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_AuthenticateRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031AuthenticateRequest.proto\022\002im\032\021Request" +
      "Type.proto\"\223\001\n\023AuthenticateRequest\022\025\n\rcl" +
      "ientVersion\030\001 \001(\005\022$\n\013requestType\030\002 \001(\0162\017" +
      ".im.RequestType\022\020\n\010sequence\030\003 \001(\003\022\013\n\003uid" +
      "\030\004 \001(\t\022\r\n\005token\030\005 \001(\t\022\021\n\ttimestamp\030\006 \001(\003" +
      "B1\n\025com.lynch.im.protocolB\030AuthenticateR" +
      "equestProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lynch.im.protocol.RequestTypeProto.getDescriptor(),
        });
    internal_static_im_AuthenticateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_AuthenticateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_AuthenticateRequest_descriptor,
        new java.lang.String[] { "ClientVersion", "RequestType", "Sequence", "Uid", "Token", "Timestamp", });
    com.lynch.im.protocol.RequestTypeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
